name: sls-fargate

on:
  workflow_call:
  push:
    branches:
      - main

jobs:
  Deploy:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: us-east-1
      STAGE: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Logging
        run: printenv
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Package
        run: npx serverless package
      - name: Deploy to Dev
        run: npx serverless deploy --stage dev --verbose --package .serverless